package.json, webpack.config.js
Added webpack config file and package.json scripts
=> Frontend boilerplate

functions/firebase-debug.log, functions/index.js, package.json, webpack.config.js
Updated package JSON to include frontend dependancies.
=> added dependencies

client/app.js, client/components/Main.jsx, client/components/index.js, client/index.js, client/routes/routes.js, client/store/hello.js, client/store/index.js, package-lock.json, package.json, public/index.html
Rearrange boilerplate code to eliminate all rendering errors, and implement a simple 'Hello World' as proof of functionality
=> Hello word test

.gitignore, client/components/Navbar.jsx, public/index.html, public/style.css
There isn't any functionality yet, but the navbar is rendering properly
=> Added navbar

client/components/EditTimeline.jsx, client/components/Timeline.js, package.json
SVG element displaying in edit timeline. Changed sidebar to always be visible.
=> Basic svg element rendering in edit timeline

functions/index.js
Be sure to "npm uninstall express" in both root and the functions directory
=> Uninstall express

functions/index.js
Exported app in firebase index
=> Fixed firebase error

client/components/PieChart.js, client/components/TestVisual.js, client/components/Timeline.js, client/components/index.js, client/routes/routes.js, package.json, public/style.css
Rendering a chart on localhost5000/barchart. Component updates when submit button is pressed. Only accepts one new value at a time.
=> Visual test 38

public/style.css, src/App.js, src/components/AllTimelines.js, src/components/SankeyWrapper.js, src/components/SingleSelection.js
Fixed the styling issue on landing page, added flex layout to all timelines grid, slightly changed sankey diagram formatting.
=> Styling changes to all charts view and sankey diagram

src/components/SignUp.js
Needs redirct but otherwise working.
=> signup working

src/components/Navbar.jsx, src/components/index.js, src/store/user.js
Login and out through nav working.
=> Nav login out

src/components/Navbar.jsx, src/store/user.js
Logout and Nav redirect now working.
=> nav-redirect

public/style.css, src/components/AllTimelines.js, src/components/BarChart.js, src/components/BarChartTools.js, src/components/BarChartUtils/BarChartJSONUtil.js, src/components/Editor.js, src/components/Editor2.js, src/components/Sankey.js, src/components/Toolbar.js, src/components/charts/bar.js, src/components/toolbars/bar.js, src/routes/routes.js, src/store/barChart.js, src/store/index.js
Bar Chart JSON import Export
Bar Chart Tools Styling.
=> Bar chart json

src/components/PublishButton.js, src/components/index.js, src/components/toolbars/bar.js
Publish button that displays modal for missing info (No Chart title, or user not logged in)
=> Publish button

public/style.css, src/components/AllTimelines.js, src/components/BarChart.js, src/components/PresentationView.js, src/components/PublishButton.js, src/components/index.js, src/routes/routes.js
Basic presentation view,
Bar Chart styling improvements
=> Presentation view

public/style.css, src/components/SankeyWrapper.js
Sidebar no longer shifts position based on size of chart
=> Made tools sidebar static component on sankey

src/components/layout/SingleSelection.js, src/components/views/AllProjects.js
allprojects view renders with link to single chart view
=> can link to single views

src/App.js, src/components/toolbars/tools/PublishButton.js, src/database/auth.js, src/routes/routes.js
Reloading now redirects to page you were on... eventually.
=> Reload url

public/style.css, src/components/TimelineWrapper.js, src/components/charts/Timeline.js, src/components/toolbars/TimelineTools.js
Timeline toolbar functionality is working, except for the edit start and end dates.
=> Add timeline

src/components/TimelineWrapper.js, src/components/charts/Timeline.js, src/components/toolbars/SankeyUtils/FooterBar.js, src/components/toolbars/TimelineTools.js, src/store/timeline.js
All DB data from timelineWrapper is fully controlled in redux-store.
=> Json timeline

src/components/SankeyWrapper.js, src/components/TimelineWrapper.js, src/store/sankeyChart.js
allows sankey load after route refactor.
=> sankey-load-saved-fixed

src/components/SankeyWrapper.js
=> Sankey add link fixed

src/components/SankeyWrapper.js, src/components/toolbars/SankeyUtils/FooterBar.js, src/components/toolbars/SankeyUtils/utils.js, src/components/toolbars/TimelineTools.js, src/store/sankeyChart.js
Sankey is now fully functional.
=> Fix sankey

public/style.css, src/components/TimelineWrapper.js, src/components/toolbars/TimelineModal.js, src/store/timeline.js
Transitioned timeline modal to use semantic. Adjusted formatting of modal elements.
=> Semantic modal

src/components/SankeyWrapper.js, src/components/toolbars/SankeyUtils/FooterBar.js, src/components/toolbars/TimelineModal.js, src/components/toolbars/tools/ColorPicker.js
Adjusted margins on modal to make it easier to read.
=> Styling changes to modal

public/index.html, public/style.css, src/components/TimelineWrapper.js, src/components/toolbars/TimelineTools.js, src/components/views/AllProjects.js
Toolbar fields for timeline are now properly centered and toolbar collapses when entering presentation mode. Also added a randomizer function to all templates view that randomly outputs an image url for each chart type. We'll need to create more sample images if we want it to have a decent number to choose from -- right now the only one with multiple samples is the timeline.
=> Tool style and thumbnail randomizer

public/style.css, src/components/SankeyWrapper.js, src/components/toolbars/SankeyTools.js, src/components/toolbars/SankeyUtils/AddLink.js, src/components/toolbars/SankeyUtils/AddNode.js, src/components/views/AllProjects.js
Updated toolbar styling for sankey to match timeline. Added new thumbnails to grid view. Did not update map tools, though.
=> Tool style
